eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka/

# You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead.
# In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
      - id: food_service_route
        uri: lb://food-service
        predicates:
          - Path=/foods/*

      - id: diary_service_route
        uri: lb://diary-service
        predicates:
          - Path=/diaries/*

      - id: ask_oracle_service_route
        uri: lb://ask-oracle-service
        predicates:
          - Path=/top-richest-foods/*

management:
  endpoints:
    web:
      exposure:
        include: "*"
